services:
  frontend:
    build: ./front-end/
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
          - ./front-end:/front-end
          - /front-end/node_modules  # Prevents overwriting node_modules with host
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    
  backend:
    build: ./app/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
