<script>
    // InputData.svelte
    import { onMount } from 'svelte';
    import { classifyExoplanetFile } from '$lib/api';
    import Chart from 'chart.js/auto';
    
    // State variables
    let selectedFile = null;
    let fileName = '';
    let isLoading = false;
    let showResults = false;
    let results = null;
    
    // File input handler
    function handleFileSelect(event) {
        const file = event.target.files[0];
        if (file) {
            selectedFile = file;
            fileName = file.name;
        }
    }
    
    // Download template
    async function downloadTemplate() {
        try {
            const response = await fetch('/download-template');
            const blob = await response.blob();
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'exoplanet_input_template.csv';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            window.URL.revokeObjectURL(url);
        } catch (error) {
            alert('Error downloading template: ' + error.message);
        }
    }
    
    // Submit form
    async function handleSubmit(event) {
        event.preventDefault(); // Prevent default form submission
        if (!selectedFile) {
            alert('Please select a file before submitting.');
            return;
        }

        isLoading = true;
        showResults = false;
        results = null;

        try {
            results = await classifyExoplanetFile(selectedFile);
            showResults = true;
        } catch (error) {
            alert('Error classifying file: ' + error.message);
        } finally {
            isLoading = false;
            scrollToTop();
        }
    }
    
    // Download results
    function downloadResults() {
        if (results?.filename) {
            window.location.href = `/download-results/${results.filename}`;
        }
    }
    
    // Scroll to top
    function scrollToTop() {
        window.scrollTo({ top: 0, behavior: 'smooth' });
    }

    // Generate result chart
    let chart;
    let chartCanvas;

    
    function renderChart(distribution) {
        const labels = Object.keys(distribution);
        const data = Object.values(distribution);

        if (chart) chart.destroy(); // Clear previous chart if it exists

        chart = new Chart(chartCanvas, {
            type: 'pie',
            data: {
                labels,
                datasets: [{
                    data,
                    backgroundColor: ['#4CAF50', '#FFC107', '#F44336'],
                }]
            },
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'bottom'
                    },
                    title: {
                        display: true,
                        text: 'Exoplanet Classification Distribution'
                    }
                }
            }
        });
    }

    // Reactive statement to trigger chart rendering when results are ready
    $: if (showResults && results?.summary?.distribution) {
        renderChart(results.summary.distribution);
    }

</script>

<!-- HTML Template -->
<div class="input-data-page">
    <!-- Navigation -->
    <nav class="navbar">
        <div class="logo">
            <div class="logo-icon">
            <img src='/logo.png' class='w-24'>
            </div>
            <span>MD-2R</span>
        </div>
        <div class="nav-links">
            <a href="/input">Input Data</a>
            <a href="/baseDeDados">Database</a>
            <a href="/AboutUs">About Us</a>
        </div>
    </nav>

    <!-- Hero Section -->
    <section class="hero">
        <h1>Input Data</h1>
        <p>
            This page is where you submit astronomical data for analysis by our AI. 
            The process is simple: just download the template, upload your data file, 
            and submit it for classification. You can then view the clear and detailed 
            results generated by the model, complete with explanations and charts.
        </p>
    </section>

    <!-- Main Content -->
    <div class="container">
        <!-- Mass Upload Card -->
        <div class="upload-card">
            <h2>Mass Upload</h2>
            <p class="subtitle">Insert your data to analyse</p>
            
            <div class="upload-description">
                Ready to test your data? To ensure our AI can correctly interpret the information, 
                we ask that you follow our standard format. First, 
                <button class="link-button" on:click={downloadTemplate}>download our guide template</button>. 
                After filling it with the data for your potential exoplanet, return here to 
                <strong>upload the completed file</strong>.
            </div>

            <form on:submit={handleSubmit}>
                <div class="upload-grid">
                    <!-- Template Section -->
                    <div class="upload-section">
                        <h3>Template</h3>
                        <p>
                            For instructions, hover over the column headers. The comments explain 
                            the formatting and specify which columns are mandatory or recommended 
                            for an accurate analysis.
                        </p>
                        <button type="button" class="btn btn-primary" on:click={downloadTemplate}>
                            Download Template
                        </button>
                    </div>

                    <!-- Load Section -->
                    <div class="upload-section">
                        <h3>Load</h3>
                        <p>
                            Test our technology: prepare your astronomical data using our template, 
                            submit it to our AI, and receive a complete, detailed analysis.
                        </p>
                        <div class="file-input-wrapper">
                            <button 
                                type="button" 
                                class="btn btn-primary" 
                                on:click={() => document.getElementById('fileInput').click()}
                            >
                                Upload .xlsm
                            </button>
                            <input 
                                type="file" 
                                id="fileInput" 
                                accept=".xlsx,.xls,.csv" 
                                on:change={handleFileSelect}
                                style="display: none;"
                            />
                        </div>
                        {#if fileName}
                            <div class="file-name">Selected: {fileName}</div>
                        {/if}
                    </div>

                    <!-- Submit Button -->
                    <button 
                        type="submit" 
                        class="btn btn-submit" 
                        disabled={isLoading}
                    >
                        {isLoading ? 'Processing...' : 'Submit'}
                    </button>
                </div>
            </form>

            {#if isLoading}
                <div class="loading">
                    <div class="spinner"></div>
                    <p>Processing your data...</p>
                </div>
            {/if}
        </div>

        <!-- Results Section -->
        {#if showResults && results}
            <div class="results-card" id="resultsSection">
                <h2>Results</h2>
                <p class="subtitle">Check your</p>
                
                <div class="results-content">
                    <div class="results-summary">
                        <h3>✨ Analysis Complete!</h3>
                        <p>Processed {results.length} exoplanets</p>
                    </div>

                    <!-- Chart Container -->
                    <div class="chart-container">
                        <h3>Classification distribution</h3>
                        <canvas bind:this={chartCanvas}></canvas>
                    </div>

                    <div class="results-description">
                        <p>
                            Your detailed analysis has been generated with classifications, 
                            confidence scores, and feature importance for each exoplanet. 
                            Download the complete results file to view all the data and insights.
                        </p>
                    </div>

                    <button class="btn btn-primary" on:click={downloadResults}>
                        Download Results
                    </button>
                </div>
            </div>
        {/if}
    </div>

    <!-- Scroll to Top Button -->
    <button class="scroll-top" on:click={scrollToTop} aria-label="Scroll to top">
        ↑
    </button>

    <!-- Footer -->
    <footer>
        <div class="footer-content">
            <div class="footer-logo">
                <div class="logo-icon">🌍</div>
                <span>MD-2R</span>
            </div>
            <div>
                <p class="footer-title">Contatos - Desenvolvedores</p>
                <div class="footer-contacts">
                    <a href="mailto:arthur_higa@hotmail.com">arthur_higa@hotmail.com</a>
                    <a href="mailto:biancabruna@gmail.com">biancabruna@gmail.com</a>
                    <a href="mailto:gabriel.giro@unicamp.br">gabriel.giro@unicamp.br</a>
                    <a href="mailto:amandsakemikato@gmail.com">amandsakemikato@gmail.com</a>
                    <a href="mailto:everton.m@gmail.com">everton.m@gmail.com</a>
                    <a href="mailto:samuel.parkour@outlook.com">samuel.parkour@outlook.com</a>
                </div>
            </div>
        </div>
    </footer>
</div>

<style>
    :global(body) {
        margin: 0;
        padding: 0;
        font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    }

    .input-data-page {
        background: linear-gradient(180deg, #4A6B7C 0%, #1a2f3d 100%);
        color: white;
        min-height: 100vh;
    }

    /* Navbar */
    .navbar {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 20px 60px;
        background: rgba(74, 107, 124, 0.8);
        backdrop-filter: blur(10px);
        position: sticky;
        top: 0;
        z-index: 100;
    }

    .logo {
        display: flex;
        align-items: center;
        gap: 12px;
        font-size: 24px;
        font-weight: 700;
    }

    .logo-icon {
        width: 40px;
        height: 40px;
        border-radius: 50%;
        background: white;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .nav-links {
        display: flex;
        gap: 40px;
        align-items: center;
    }

    .nav-links a {
        color: white;
        text-decoration: none;
        font-size: 16px;
        transition: opacity 0.3s;
    }

    .nav-links a:hover {
        opacity: 0.8;
    }

    .get-in-touch {
        padding: 10px 24px;
        border: 2px solid white;
        border-radius: 25px;
        transition: all 0.3s;
    }

    .get-in-touch:hover {
        background: white;
        color: #4A6B7C;
    }

    /* Hero Section */
    .hero {
        padding: 80px 60px 60px;

        
    }

    .hero h1 {
        font-size: 72px;
        font-weight: 700;
        margin-bottom: 20px;
    }

    .hero p {
        font-size: 18px;
        line-height: 1.6;
        max-width: 800px;
        opacity: 0.9;
    }

    /* Container */
    .container {
        max-width: 1200px;
        margin: 0 auto;
        padding: 40px 60px;
    }

    /* Upload Card */
    .upload-card {
        background: rgba(22, 66, 100, 0.6);
        backdrop-filter: blur(10px);
        border-radius: 20px;
        padding: 50px;
        margin-bottom: 40px;
        border: 1px solid rgba(255, 255, 255, 0.1);
    }

    .upload-card h2 {
        font-size: 48px;
        font-style: italic;
        font-weight: 700;
        text-align: center;
        margin-bottom: 10px;
    }

    .subtitle {
        text-align: center;
        opacity: 0.8;
        margin-bottom: 30px;
        font-size: 14px;
    }

    .upload-description {
        text-align: center;
        margin-bottom: 40px;
        line-height: 1.6;
    }

    .link-button {
        background: none;
        border: none;
        color: #6EC1E4;
        text-decoration: underline;
        cursor: pointer;
        font-size: inherit;
        font-family: inherit;
        padding: 0;
    }

    .link-button:hover {
        opacity: 0.8;
    }

    .upload-grid {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 30px;
        margin-bottom: 30px;
    }

    .upload-section {
        background: rgba(30, 45, 60, 0.5);
        padding: 30px;
        border-radius: 15px;
    }

    .upload-section h3 {
        font-size: 20px;
        margin-bottom: 15px;
    }

    .upload-section p {
        font-size: 14px;
        line-height: 1.5;
        opacity: 0.8;
        margin-bottom: 20px;
    }

    .btn {
        width: 100%;
        padding: 15px;
        border: none;
        border-radius: 10px;
        font-size: 16px;
        font-weight: 600;
        cursor: pointer;
        transition: all 0.3s;
    }

    .btn:disabled {
        opacity: 0.5;
        cursor: not-allowed;
    }

    .btn-primary {
        background: rgba(70, 120, 150, 0.8);
        color: white;
        border: 1px solid rgba(255, 255, 255, 0.2);
    }

    .btn-primary:hover:not(:disabled) {
        background: rgba(70, 120, 150, 1);
        transform: translateY(-2px);
    }

    .btn-submit {
        background: rgba(50, 80, 100, 0.8);
        color: white;
        border: 1px solid rgba(255, 255, 255, 0.2);
        grid-column: 1 / -1;
    }

    .btn-submit:hover:not(:disabled) {
        background: rgba(50, 80, 100, 1);
        transform: translateY(-2px);
    }

    .file-input-wrapper {
        position: relative;
    }

    .file-name {
        margin-top: 10px;
        font-size: 14px;
        color: #6EC1E4;
        text-align: center;
    }

    /* Loading */
    .loading {
        text-align: center;
        padding: 20px;
        margin-top: 20px;
    }

    .spinner {
        border: 3px solid rgba(255, 255, 255, 0.3);
        border-top: 3px solid white;
        border-radius: 50%;
        width: 40px;
        height: 40px;
        animation: spin 1s linear infinite;
        margin: 0 auto 15px;
    }

    @keyframes spin {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
    }

    /* Results Card */
    .results-card {
        background: rgba(40, 60, 75, 0.6);
        backdrop-filter: blur(10px);
        border-radius: 20px;
        padding: 50px;
        border: 1px solid rgba(255, 255, 255, 0.1);
    }

    .results-card h2 {
        font-size: 48px;
        font-style: italic;
        font-weight: 700;
        text-align: center;
        margin-bottom: 10px;
    }

    .results-content {
        background: rgba(30, 45, 60, 0.5);
        padding: 30px;
        border-radius: 15px;
    }

    .results-summary {
        margin-bottom: 20px;
    }

    .results-summary h3 {
        font-size: 24px;
        margin-bottom: 10px;
    }

    .chart-container {
        background: white;
        border-radius: 15px;
        padding: 30px;
        margin: 20px 0;
        color: #333;
    }

    .results-description {
        margin: 20px 0;
        line-height: 1.6;
    }

    /* Scroll to Top */
    .scroll-top {
        position: fixed;
        bottom: 40px;
        right: 40px;
        width: 50px;
        height: 50px;
        border-radius: 50%;
        background: rgba(70, 120, 150, 0.8);
        border: 1px solid rgba(255, 255, 255, 0.2);
        display: flex;
        align-items: center;
        justify-content: center;
        cursor: pointer;
        transition: all 0.3s;
        font-size: 24px;
        color: white;
    }

    .scroll-top:hover {
        background: rgba(70, 120, 150, 1);
        transform: translateY(-5px);
    }




    /* Responsive */
    @media (max-width: 768px) {
 

        .hero {
            padding: 40px 20px;
        }

        .hero h1 {
            font-size: 42px;
        }

        .container {
            padding: 20px;
        }

        .upload-card, .results-card {
            padding: 30px 20px;
        }

        .upload-grid {
            grid-template-columns: 1fr;
        }
    
    }

</style>
